# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: centralizer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x65ntralizer.proto\x12\x0b\x63\x65ntralizer\";\n\x0fRegisterRequest\x12\x1a\n\x12service_identifier\x18\x01 \x01(\t\x12\x0c\n\x04keys\x18\x02 \x03(\x05\"\x19\n\nMapRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\")\n\x0bMapResponse\x12\x1a\n\x12service_identifier\x18\x01 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2\xc0\x01\n\x0b\x43\x65ntralizer\x12?\n\x08Register\x12\x1c.centralizer.RegisterRequest\x1a\x15.centralizer.Response\x12\x38\n\x03Map\x12\x17.centralizer.MapRequest\x1a\x18.centralizer.MapResponse\x12\x36\n\tTerminate\x12\x12.centralizer.Empty\x1a\x15.centralizer.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'centralizer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REGISTERREQUEST']._serialized_start=34
  _globals['_REGISTERREQUEST']._serialized_end=93
  _globals['_MAPREQUEST']._serialized_start=95
  _globals['_MAPREQUEST']._serialized_end=120
  _globals['_MAPRESPONSE']._serialized_start=122
  _globals['_MAPRESPONSE']._serialized_end=163
  _globals['_RESPONSE']._serialized_start=165
  _globals['_RESPONSE']._serialized_end=191
  _globals['_EMPTY']._serialized_start=193
  _globals['_EMPTY']._serialized_end=200
  _globals['_CENTRALIZER']._serialized_start=203
  _globals['_CENTRALIZER']._serialized_end=395
# @@protoc_insertion_point(module_scope)
