# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pair.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npair.proto\x12\x04pair\"%\n\x07Request\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t\"!\n\x10RetrieveResponse\x12\r\n\x05value\x18\x01 \x01(\t\"-\n\x0f\x41\x63tivateRequest\x12\x1a\n\x12service_identifier\x18\x01 \x01(\t\"\"\n\x10\x41\x63tivateResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\n\n\x08Response\"\x19\n\nMapRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\")\n\x0bMapResponse\x12\x1a\n\x12service_identifier\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xf3\x01\n\x04Pair\x12\'\n\x06Insert\x12\r.pair.Request\x1a\x0e.pair.Response\x12*\n\x03Map\x12\x10.pair.MapRequest\x1a\x11.pair.MapResponse\x12\x31\n\x08Retrieve\x12\r.pair.Request\x1a\x16.pair.RetrieveResponse\x12\x39\n\x08\x41\x63tivate\x12\x15.pair.ActivateRequest\x1a\x16.pair.ActivateResponse\x12(\n\tTerminate\x12\x0b.pair.Empty\x1a\x0e.pair.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pair_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=20
  _globals['_REQUEST']._serialized_end=57
  _globals['_RETRIEVERESPONSE']._serialized_start=59
  _globals['_RETRIEVERESPONSE']._serialized_end=92
  _globals['_ACTIVATEREQUEST']._serialized_start=94
  _globals['_ACTIVATEREQUEST']._serialized_end=139
  _globals['_ACTIVATERESPONSE']._serialized_start=141
  _globals['_ACTIVATERESPONSE']._serialized_end=175
  _globals['_RESPONSE']._serialized_start=177
  _globals['_RESPONSE']._serialized_end=187
  _globals['_MAPREQUEST']._serialized_start=189
  _globals['_MAPREQUEST']._serialized_end=214
  _globals['_MAPRESPONSE']._serialized_start=216
  _globals['_MAPRESPONSE']._serialized_end=257
  _globals['_EMPTY']._serialized_start=259
  _globals['_EMPTY']._serialized_end=266
  _globals['_PAIR']._serialized_start=269
  _globals['_PAIR']._serialized_end=512
# @@protoc_insertion_point(module_scope)
